services:
  app-1:
    build:
      context: .
      dockerfile: Dockerfile

  app-2:
    build:
      context: .
      dockerfile: Dockerfile

  app-3:
    build:
      context: .
      dockerfile: Dockerfile

  balancer:
    image: nginx:alpine3.21
    ports:
      - 6080:80
    volumes:
      - ./nginx:/etc/nginx/templates
